# docker-compose.yml

version: '3.8'
services:
  playwright-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests:/app/tests
      - ./playwright.config.js:/app/playwright.config.js
    working_dir: /app
    command: npx playwright test

